import "../assets/style/style.scss";
import Toggle from "./toggle/page";
import SideBar from "./sidebar/page.jsx";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Toggle />
        <SideBar />
        {children}
        </body>
    </html>
  )
}
